### ISSUE TITLE
documentation missing

### ISSUE THREAD

**Issue by taf2** [gsuitedevs/ruby-samples#7] opened 2018-07-30 15:25 UTC
There is a general lack of how to authenticate with most of google ruby gems.   The credentials.json file is not well documented..  each project should explicitly provide instructions for setting this up... IMO this is a big barrier to entry with google projects and code in general...

**Comment by erickoledadevrel** [comment] 2018-07-30 16:50
Thanks for the feedback, we can certainly do a lot more to improve the documentation around the core libraries. In this case, the issue would be best posted on the auth library's issue tracker:

https://github.com/google/google-auth-library-ruby/issues

I don't think I can transfer your issue to that repo, so closing it here and requesting you reopen it there.

**Comment by erickoledadevrel** [comment] 2018-07-30 18:50
Re-opening to discuss :-) 

I agree that it would be ideal if all the information you needed to work with an API was all in one location, but with an organization the size of Google I'm not sure it's feasible. As you can see, this repo alone has samples for a dozen APIs, and that's just within the G Suite family of APIs. Having information about how to use the Ruby library replicated in dozens of places is bad SEO, and it could more easily fall out of date. 

Our approach so far has been to create the Quickstart guides, which try to show at least one path that stitches together the various systems and has clear pointers off to the other resources you need to read. I think information about the behavior of a specific method, like `from_hash()`, really belongs in some central place rather than copied dozens of times.

Would it help if we cross-linked more to the Ruby client library docs? Other ideas?

**Comment by taf2** [comment] 2018-07-30 21:59
Google has a lot of engineering resources... this sounds like a problem that software could solve right?  Automated documentation... e.g. in ruby

README.md

```
<%= render_auth_logic %>
```

... just saying i think big company or not a solution exists?

**Comment by grant** [comment] 2018-08-02 03:52
Thanks for the feedback. I'm not sure what the problem is with this specific repo (gsuitedevs/ruby-samples).

> Automated documentation... e.g. in ruby

We have automated docs here: https://www.rubydoc.info/github/google/google-api-ruby-client/Google/APIClient

Is there something more specific you're looking for?

Perhaps we can document the set-up a bit more in 
https://cloud.google.com/docs/authentication/production
or give more links to helpful resources.

**Comment by taf2** [comment] 2018-08-02 04:05
example: 

   https://github.com/gsuitedevs/ruby-samples/tree/master/gmail/quickstart

try running the example as described... 

```
gem install google-api-client
ruby quickstart.rb
taf2~/work/foo> ruby quickstart.rb
/Users/taf2/.rvm/gems/ruby-2.4.1/gems/googleauth-0.6.2/lib/googleauth/client_id.rb:80:in `initialize': No such file or directory @ rb_sysopen - credentials.json (Errno::ENOENT)
	from /Users/taf2/.rvm/gems/ruby-2.4.1/gems/googleauth-0.6.2/lib/googleauth/client_id.rb:80:in `open'
	from /Users/taf2/.rvm/gems/ruby-2.4.1/gems/googleauth-0.6.2/lib/googleauth/client_id.rb:80:in `from_file'
	from quickstart.rb:33:in `authorize'
	from quickstart.rb:53:in `<main>' 
```

The issue is not that I can't figure this out it's that I have to dig around to figure it out... It seems common over pretty much all google client libraries... at least node and ruby share this issue... which i agree isn't a huge issue it's just more of a annoyance and i wanted to point out that I think it makes it a lot harder people starting out to figure out how to approach the apis... maybe this is the wrong place to report but maybe it's an okay place?

**Comment by erickoledadevrel** [comment] 2018-08-27 18:57
Thanks again for your feedback, and we'll take some time to brainstorm ways we can improve the learning experience that don't require you to consult so many different resources. Given that the core problem isn't specific to these ruby samples, I'm going to close this issue. But feel free to continue the conversation with me on Twitter or G+:

https://twitter.com/erickoleda/
https://plus.google.com/+EricKoleda

**Closed by erickoledadevrel** 2018-08-27 18:57 UTC

**Comment by JikkuJose** [comment] 2020-10-08 19:18
Running the quickstart.rb is still giving the same error. Any ideas to solve it?

```
/Users/username/.gem/ruby/2.7.1/gems/googleauth-0.13.1/lib/googleauth/client_id.rb:82:in `initialize': No such file or directory @ rb_sysopen - credentials.json (Errno::ENOENT)
	from /Users/username/.gem/ruby/2.7.1/gems/googleauth-0.13.1/lib/googleauth/client_id.rb:82:in `open'
	from /Users/username/.gem/ruby/2.7.1/gems/googleauth-0.13.1/lib/googleauth/client_id.rb:82:in `from_file'
	from qs.rb:22:in `authorize'
/Users/username/.gem/ruby/2.7.1/gems/googleauth-0.13.1/lib/googleauth/client_id.rb:82:in `initialize': No such file or directory @ rb_sysopen - credentials.json (Errno::ENOENT)
	from /Users/username/.gem/ruby/2.7.1/gems/googleauth-0.13.1/lib/googleauth/client_id.rb:82:in `open'
	from /Users/username/.gem/ruby/2.7.1/gems/googleauth-0.13.1/lib/googleauth/client_id.rb:82:in `from_file'
	from qs.rb:22:in `authorize'
	from qs.rb:42:in `<main>'
	from qs.rb:42:in `<main>'
```
